# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_MINOR_VERSION
tag-template: $NEXT_MINOR_VERSION
version-template: $MAJOR.$MINOR

# https://gitmoji.carloscuesta.me/
categories:
  - title: 🚨 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: :package: Dependency updates
    label: dependencies
  - title: 📝 Documentation updates
    label: documentation
  - title: 🚦 Internal changes
    label: internal
exclude-labels:
  - reverted
  - no-changelog

template: |
  ## Changes
  $CHANGES

#replacers:
#  - search: '/\[*JENKINS-(\d+)\]*/g'
#    replace: '[$1](https://issues.jenkins-ci.org/browse$1)'

# TODO: Probot docs
